### ISSUE TITLE
Build problem under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [Clozure/ccl#205]

**Comment by stefanhusmann** [comment]
Under Arch Linux I maintain a package for x86_64. Recently I get have a problem with compiling the package, because the compile process seems to hang. No error message. 

The process hangs at this point:
```
cc  -m64 -g  -Wl,--export-dynamic "-Wl,--hash-style=sysv" -o ../../lx86cl64  pad.o x86-spjump64.o x86-spentry64.o x86-subprims64.o pmcl-kernel.o gc-common.o x86-gc.o bits.o  x86-exceptions.o x86-utils.o image.o thread_manager.o lisp-debug.o memory.o unix-calls.o x86-asmutils64.o  imports.o lispdcmd.o plprint.o plsym.o xlbt.o x86_print.o -Wl,--no-as-needed -ldl -lm -lpthread -lrt
Rebuilding Clozure Common Lisp using Version 1.12-dev/v1.12-dev.1  (LinuxX8664)
;Compiling "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/lib/systems.lisp"...
;Loading #P"/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/bin/systems.lx64fsl"...
;Compiling "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/lib/compile-ccl.lisp"...
;Loading #P"/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/bin/compile-ccl.lx64fsl"...
;Compiling "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/compiler/nxenv.lisp"...
;Loading #P"/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/bin/nxenv.lx64fsl"...
;Compiling "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/compiler/nx.lisp"...
; Including "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/compiler/nx-basic.lisp"...
; Including "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/compiler/lambda-list.lisp"...
; Including "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/compiler/nx0.lisp"...
; Including "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/compiler/nx1.lisp"...
;Loading #P"/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/l1-fasls/nx.lx64fsl"...
;Compiling "/home/haawda/paketierung/meine_Pakete/ccl-git/src/ccl/compiler/optimizers.lisp"...
 ```
The strace -p says 
```
futex(0x5648159ffad0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5648159ffb00, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
nanosleep({tv_sec=0, tv_nsec=29001530}, 0x7fffff20ae50) = 0
nanosleep({tv_sec=0, tv_nsec=330000000}, {tv_sec=0, tv_nsec=308254506}) = ? ERESTART_RESTARTBLOCK (Interrupted by signa
l)
--- SIGRT_8 {si_signo=SIGRT_8, si_code=SI_TKILL, si_pid=20578, si_uid=1000} ---
futex(0x5648159ffad0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5648159ffb00, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
nanosleep({tv_sec=0, tv_nsec=308254506}, {tv_sec=0, tv_nsec=260318889}) = ? ERESTART_RESTARTBLOCK (Interrupted by signa
l)
--- SIGRT_8 {si_signo=SIGRT_8, si_code=SI_TKILL, si_pid=20578, si_uid=1000} ---
futex(0x5648159ffad0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5648159ffb00, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
nanosleep({tv_sec=0, tv_nsec=260318889}, {tv_sec=0, tv_nsec=211567334}) = ? ERESTART_RESTARTBLOCK (Interrupted by signa
l)
--- SIGRT_8 {si_signo=SIGRT_8, si_code=SI_TKILL, si_pid=20578, si_uid=1000} ---
futex(0x5648159ffad0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5648159ffb00, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
nanosleep({tv_sec=0, tv_nsec=211567334}, ^Cstrace: Process 20578 detached
 <detached ...>
```

**Comment by tacho** [comment]
Compiling latest HEAD under macOS 10.14 Mojave, it hangs on the same file. Trace is:

```
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#60
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
__semwait_signal(0x1403, 0x0, 0x1)		 = -1 Err#4
sigreturn(0x7FFEEFBFE920, 0x1E, 0x7FFEEFBFE920)		 = 0 Err#-2
__pthread_canceled(0x0, 0x0, 0x0)		 = -1 Err#22
__pthread_kill(0x307, 0x1F, 0x0)		 = 0 0
```

**Comment by xrme** [comment]
I'll be uploading new bootstrapping binaries tonight (for Linux and macOS at least), and that should solve this.

**Comment by xrme** [comment]
I added new bootstrapping binaries for Linux/x86 and macOS.  Other platforms will follow.

https://github.com/Clozure/ccl/releases/tag/v1.12-dev.5

Please use these bootstrapping binaries in order to compile current sources.

**Comment by tacho** [comment]
I can confirm it works on macOS, thank you.

**Comment by ManfredGahr** [comment]
Still not building for armv7 due to missing bootstrapping binaries...
